{% set name = "evaluate" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/evaluate-{{ version }}.tar.gz
  sha256: d721d9f2059ced79770d8a0509e954fbd1bbac96a8f9160e29888d8073cda3d9

build:
  noarch: python
  entry_points:
    - evaluate-cli=evaluate.commands.evaluate_cli:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - datasets >=2.0.0
    - numpy >=1.17
    - dill
    - pandas
    - requests >=2.19.0
    - tqdm >=4.62.1
    - python-xxhash
    - multiprocess
    - importlib-metadata
    - fsspec >=2021.05.0
    - huggingface_hub >=0.7.0
    - packaging
    - responses <0.19
    - cookiecutter

test:
  imports:
    - evaluate
  commands:
    - pip check
    - evaluate-cli --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/huggingface/evaluate
  summary: HuggingFace community-driven open-source library of evaluation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wietsedv
